require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncollectionsController do

  # This should return the minimal set of attributes required to create a valid
  # Incollection. As you add validations to Incollection, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "author" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IncollectionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all incollections as @incollections" do
      incollection = Incollection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:incollections).should eq([incollection])
    end
  end

  describe "GET show" do
    it "assigns the requested incollection as @incollection" do
      incollection = Incollection.create! valid_attributes
      get :show, {:id => incollection.to_param}, valid_session
      assigns(:incollection).should eq(incollection)
    end
  end

  describe "GET new" do
    it "assigns a new incollection as @incollection" do
      get :new, {}, valid_session
      assigns(:incollection).should be_a_new(Incollection)
    end
  end

  describe "GET edit" do
    it "assigns the requested incollection as @incollection" do
      incollection = Incollection.create! valid_attributes
      get :edit, {:id => incollection.to_param}, valid_session
      assigns(:incollection).should eq(incollection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Incollection" do
        expect {
          post :create, {:incollection => valid_attributes}, valid_session
        }.to change(Incollection, :count).by(1)
      end

      it "assigns a newly created incollection as @incollection" do
        post :create, {:incollection => valid_attributes}, valid_session
        assigns(:incollection).should be_a(Incollection)
        assigns(:incollection).should be_persisted
      end

      it "redirects to the created incollection" do
        post :create, {:incollection => valid_attributes}, valid_session
        response.should redirect_to(Incollection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved incollection as @incollection" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incollection.any_instance.stub(:save).and_return(false)
        post :create, {:incollection => { "author" => "invalid value" }}, valid_session
        assigns(:incollection).should be_a_new(Incollection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Incollection.any_instance.stub(:save).and_return(false)
        post :create, {:incollection => { "author" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested incollection" do
        incollection = Incollection.create! valid_attributes
        # Assuming there are no other incollections in the database, this
        # specifies that the Incollection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Incollection.any_instance.should_receive(:update).with({ "author" => "MyString" })
        put :update, {:id => incollection.to_param, :incollection => { "author" => "MyString" }}, valid_session
      end

      it "assigns the requested incollection as @incollection" do
        incollection = Incollection.create! valid_attributes
        put :update, {:id => incollection.to_param, :incollection => valid_attributes}, valid_session
        assigns(:incollection).should eq(incollection)
      end

      it "redirects to the incollection" do
        incollection = Incollection.create! valid_attributes
        put :update, {:id => incollection.to_param, :incollection => valid_attributes}, valid_session
        response.should redirect_to(incollection)
      end
    end

    describe "with invalid params" do
      it "assigns the incollection as @incollection" do
        incollection = Incollection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incollection.any_instance.stub(:save).and_return(false)
        put :update, {:id => incollection.to_param, :incollection => { "author" => "invalid value" }}, valid_session
        assigns(:incollection).should eq(incollection)
      end

      it "re-renders the 'edit' template" do
        incollection = Incollection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Incollection.any_instance.stub(:save).and_return(false)
        put :update, {:id => incollection.to_param, :incollection => { "author" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested incollection" do
      incollection = Incollection.create! valid_attributes
      expect {
        delete :destroy, {:id => incollection.to_param}, valid_session
      }.to change(Incollection, :count).by(-1)
    end

    it "redirects to the incollections list" do
      incollection = Incollection.create! valid_attributes
      delete :destroy, {:id => incollection.to_param}, valid_session
      response.should redirect_to(incollections_url)
    end
  end

end
