require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InproceedingsController do

  # This should return the minimal set of attributes required to create a valid
  # Inproceedings. As you add validations to Inproceedings, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "author" => "Tero Keinanen", 
                             "title" => "Miksi en pida Railsista",
                             "booktitle" => "Oikeamielisten kokoontuminen",
                             "year" => "2013"} }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InproceedingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all inproceedings as @inproceedings" do
      inproceedings = Inproceedings.create! valid_attributes
      get :index, {}, valid_session
      assigns(:inproceedings).should eq([inproceedings])
    end
  end

  describe "GET show" do
    it "assigns the requested inproceedings as @inproceedings" do
      inproceedings = Inproceedings.create! valid_attributes
      get :show, {:id => inproceedings.to_param}, valid_session
      assigns(:inproceedings).should eq(inproceedings)
    end
  end

  describe "GET new" do
    it "assigns a new inproceedings as @inproceedings" do
      get :new, {}, valid_session
      assigns(:inproceedings).should be_a_new(Inproceedings)
    end
  end

  describe "GET edit" do
    it "assigns the requested inproceedings as @inproceedings" do
      inproceedings = Inproceedings.create! valid_attributes
      get :edit, {:id => inproceedings.to_param}, valid_session
      assigns(:inproceedings).should eq(inproceedings)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Inproceedings" do
        expect {
          post :create, {:inproceedings => valid_attributes}, valid_session
        }.to change(Inproceedings, :count).by(1)
      end

      it "assigns a newly created inproceedings as @inproceedings" do
        post :create, {:inproceedings => valid_attributes}, valid_session
        assigns(:inproceedings).should be_a(Inproceedings)
        assigns(:inproceedings).should be_persisted
      end

      it "redirects to the created inproceedings" do
        post :create, {:inproceedings => valid_attributes}, valid_session
        response.should redirect_to(Inproceedings.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inproceedings as @inproceedings" do
        # Trigger the behavior that occurs when invalid params are submitted
        Inproceedings.any_instance.stub(:save).and_return(false)
        post :create, {:inproceedings => { "author" => "invalid value" }}, valid_session
        assigns(:inproceedings).should be_a_new(Inproceedings)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Inproceedings.any_instance.stub(:save).and_return(false)
        post :create, {:inproceedings => { "author" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inproceedings" do
        inproceedings = Inproceedings.create! valid_attributes
        # Assuming there are no other inproceedings in the database, this
        # specifies that the Inproceedings created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Inproceedings.any_instance.should_receive(:update).with({ "author" => "MyString" })
        put :update, {:id => inproceedings.to_param, :inproceedings => { "author" => "MyString" }}, valid_session
      end

      it "assigns the requested inproceedings as @inproceedings" do
        inproceedings = Inproceedings.create! valid_attributes
        put :update, {:id => inproceedings.to_param, :inproceedings => valid_attributes}, valid_session
        assigns(:inproceedings).should eq(inproceedings)
      end

      it "redirects to the inproceedings" do
        inproceedings = Inproceedings.create! valid_attributes
        put :update, {:id => inproceedings.to_param, :inproceedings => valid_attributes}, valid_session
        response.should redirect_to(inproceedings)
      end
    end

    describe "with invalid params" do
      it "assigns the inproceedings as @inproceedings" do
        inproceedings = Inproceedings.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Inproceedings.any_instance.stub(:save).and_return(false)
        put :update, {:id => inproceedings.to_param, :inproceedings => { "author" => "invalid value" }}, valid_session
        assigns(:inproceedings).should eq(inproceedings)
      end

      it "re-renders the 'edit' template" do
        inproceedings = Inproceedings.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Inproceedings.any_instance.stub(:save).and_return(false)
        put :update, {:id => inproceedings.to_param, :inproceedings => { "author" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inproceedings" do
      inproceedings = Inproceedings.create! valid_attributes
      expect {
        delete :destroy, {:id => inproceedings.to_param}, valid_session
      }.to change(Inproceedings, :count).by(-1)
    end

    it "redirects to the inproceedings list" do
      inproceedings = Inproceedings.create! valid_attributes
      delete :destroy, {:id => inproceedings.to_param}, valid_session
      response.should redirect_to(inproceedings_index_url)
    end
  end

end
